### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by mikesalz** [rsampayo/sleepme_thermostat#1]
I am excited to see that someone is working on this project!  I am happy to help test.  I tried adding to HA today and received the error below:

![image](https://github.com/user-attachments/assets/01eb112f-4d88-450d-b214-34765d3918c9)

![image](https://github.com/user-attachments/assets/1d2edd0a-9665-431d-bc5e-3a06c5ca5390)

**Comment by rsampayo** [comment]
Hello Mike, congrats on being the first beta tester.  Could you check your logs in setting > system> logs. And see if there is more info on the error? Also could you confirm you home assistant version?

**Comment by mikesalz** [comment]
Hi @rsampayo 
I am on HA 2024.8.1.

Below is the info from the log. In other custom components I have a config_flow.py.  But not in the sleepme_thermostat folder.  So maybe that is the issue?

```
Logger: homeassistant.config_entries
Source: config_entries.py:2871
First occurred: 4:12:53 PM (2 occurrences)
Last logged: 4:14:21 PM

Error occurred loading flow for integration sleepme_thermostat: No module named 'custom_components.sleepme_thermostat.config_flow'
```

**Comment by ChrisFontanini** [comment]
I get the same error. 
I'm also on HA 2024.8.1

`Logger: homeassistant.config_entries
Source: config_entries.py:2871
First occurred: 3:32:12 PM (1 occurrences)
Last logged: 3:32:12 PM

Error occurred loading flow for integration sleepme_thermostat: No module named 'custom_components.sleep_thermostat.config_flow'`

**Comment by rsampayo** [comment]
Yeah, I forgot to add the config_flow.py file. I also updated all the files. Please replace the files with the new ones and let me know if it works.

**Comment by ChrisFontanini** [comment]
That fixed it, thanks!

**Comment by rsampayo** [comment]
The config_flow should only ask for one input. It does not show the field name (I haven't been able to fix that) it is the token. After that it should list the devices in your account and you should be able to add them one by one.

**Comment by rsampayo** [comment]
Let me know if there is anything else I could add.

**Comment by rsampayo** [comment]
FYI. I'm not sure if the low water level sensor works, I haven't tested it. Let me know if it works for you.

**Comment by ChrisFontanini** [comment]
I'll follow up about the water sensor next time it's low, I'm sure it won't be long. I was able to add both Docks without issue.

**Comment by mikesalz** [comment]
Thanks @rsampayo!  I was able to add both of our Dock Pros.  I haven't tested the functionality yet, but will do that tonight.  I have the following sensors which I already had created using rest.  Any chance you can add them to the integration?

- status.water_level
- status.is_connected

**Comment by rsampayo** [comment]
You should see a sensor inside the device called:  [Device name ] Water Level Low. Do you see it?

**Comment by mikesalz** [comment]
Yes, I do see it.  But in the API they have a separate sensor that shows the percent full.  Not sure if it helps, but here is the yaml for my rest sensors.  I have separate sensors for Water Level (percent) and one for Low Water (binary).

```
    sensor:
      - name: "Mike's Dock Pro Water Temperature"
        device_class: temperature
        unit_of_measurement: "°F"
        value_template: "{{ value_json.status.water_temperature_f|int }}"
      - name: "Mike's Dock Pro Set Water Temperature"
        device_class: temperature
        unit_of_measurement: "°F"
        value_template: "{{ value_json.control.set_temperature_f|int }}"
      - name: "Mike's Dock Pro Water Level"
        device_class: moisture
        unit_of_measurement: "%"
        value_template: "{{ value_json.status.water_level }}"
      - name: "Mike's Dock Pro Status"
        value_template: "{{ value_json.control.thermal_control_status }}"
    binary_sensor:
      - name: "Mike's Dock Pro Connected"
        device_class: connectivity
        value_template: "{{ value_json.status.is_connected }}"
      - name: "Mike's Dock Pro Low Water"
        device_class: moisture
        value_template: "{{ value_json.status.is_water_low }}"

```
